# Generated by Django 5.2.8 on 2025-11-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'item']},
        ),
    ]
